const works = [
  {
    id: "masaalikul-jinaan",
    title: "Masaalikul Jinaan",
    arabicTitle: "مَسَالِكُ الْجِنَان",
    author: "Cheikh Ahmadou Bamba",
    date: null,
    theme: "Éducation spirituelle",
    description: "Œuvre consacrée à l’élévation spirituelle, à la purification du cœur et aux bonnes œuvres.",
    tags: ["Spiritualité", "Éducation", "Vertus"],
    aliases: "masalikoul jinaan masaalik masalik paradis",
    source: null,
    validation: "pending",
    validatedBy: null,
    validatedAt: null,
    pageCount: null,
    audioDuration: null,
    files: { pdf: null, audio: null },
    content: { arabic: null, transcription: null, translation: null }
  },
  {
    id: "matlaboul-fawzayni",
    title: "Matlaboul Fawzayni",
    arabicTitle: "مَطْلَبُ الْفَوْزَيْنِ",
    author: "Cheikh Ahmadou Bamba",
    date: null,
    theme: "Prière et bénédictions",
    description: "Texte de dévotion et de quête des deux bonheurs, associé à la ville sainte de Touba.",
    tags: ["Touba", "Prière", "Bénédictions"],
    aliases: "matlabul fawzeyni matlaboul fawzaini",
    source: null,
    validation: "pending",
    validatedBy: null,
    validatedAt: null,
    pageCount: null,
    audioDuration: null,
    files: { pdf: null, audio: null },
    content: { arabic: null, transcription: null, translation: null }
  },
  {
    id: "jazbul-qulub",
    title: "Jazbul Qulub",
    arabicTitle: "جَذْبُ الْقُلُوب",
    author: "Cheikh Ahmadou Bamba",
    date: null,
    theme: "Éloge prophétique",
    description: "Poème d’amour, de dévotion et d’éloge consacré au Prophète Mouhammed ﷺ.",
    tags: ["Prophète", "Éloge", "Amour"],
    aliases: "jazbul khouloub jazboul kouloub prophete",
    source: null,
    validation: "pending",
    validatedBy: null,
    validatedAt: null,
    pageCount: null,
    audioDuration: null,
    files: { pdf: null, audio: null },
    content: { arabic: null, transcription: null, translation: null }
  },
  {
    id: "mawahibun-nafi",
    title: "Mawāhibun Nāfiʿ",
    arabicTitle: "مَوَاهِبُ النَّافِع",
    author: "Cheikh Ahmadou Bamba",
    date: null,
    theme: "Science et bienfaits",
    description: "Khassida évoquant les dons, les connaissances utiles et la proximité spirituelle.",
    tags: ["Savoir", "Bienfaits", "Foi"],
    aliases: "mawahibun nafi mawahibu naafi",
    source: null,
    validation: "pending",
    validatedBy: null,
    validatedAt: null,
    pageCount: null,
    audioDuration: null,
    files: { pdf: null, audio: null },
    content: { arabic: null, transcription: null, translation: null }
  },
  {
    id: "tazawwudush-shubban",
    title: "Tazawwudush Shubbān",
    arabicTitle: "تَزَوُّدُ الشُّبَّان",
    author: "Cheikh Ahmadou Bamba",
    date: null,
    theme: "Formation de la jeunesse",
    description: "Conseils spirituels, moraux et pratiques destinés notamment à la jeunesse.",
    tags: ["Jeunesse", "Conseils", "Comportement"],
    aliases: "tazawwudush shubban jeunesse",
    source: null,
    validation: "pending",
    validatedBy: null,
    validatedAt: null,
    pageCount: null,
    audioDuration: null,
    files: { pdf: null, audio: null },
    content: { arabic: null, transcription: null, translation: null }
  },
  {
    id: "munawwirus-sudur",
    title: "Munawwirus Sudūr",
    arabicTitle: "مُنَوِّرُ الصُّدُور",
    author: "Cheikh Ahmadou Bamba",
    date: null,
    theme: "Purification du cœur",
    description: "Œuvre orientée vers l’illumination des cœurs, la foi et le perfectionnement intérieur.",
    tags: ["Cœur", "Lumière", "Foi"],
    aliases: "munawwiru sudur mounawirou soudour",
    source: null,
    validation: "pending",
    validatedBy: null,
    validatedAt: null,
    pageCount: null,
    audioDuration: null,
    files: { pdf: null, audio: null },
    content: { arabic: null, transcription: null, translation: null }
  }
];

window.XASSIDA_WORKS = works;
