"use client";
import {FormEvent,useEffect,useState} from "react";
import type {Khassida,Chunk} from "@/types/database";
type Result={kind:"khassida"|"chunk";khassida:Khassida;chunk?:Chunk;score?:number};
export function SearchExperience(){const [q,setQ]=useState("");const [results,setResults]=useState<Result[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function search(e?:FormEvent){e?.preventDefault();setLoading(true);setError("");try{const res=await fetch(`/api/search?q=${encodeURIComponent(q)}`);const body=await res.json();if(!res.ok)throw new Error(body.error);setResults(body.results)}catch(err){setError(err instanceof Error?err.message:"Recherche impossible")}finally{setLoading(false)}}
 useEffect(()=>{search()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 return <section id="bibliotheque" className="section container"><div className="section-head"><div><span className="eyebrow">Explorer</span><h2>Bibliothèque validée</h2></div><span className="muted">{results.length} résultat(s)</span></div><form className="searchbar panel" onSubmit={search} style={{display:"flex",gap:10,marginBottom:25}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Titre, variante, thème, mots arabes ou passage…" aria-label="Rechercher"/><button className="button" disabled={loading}>{loading?"Recherche…":"Rechercher"}</button></form>{error&&<p className="notice">{error}</p>}<div className="grid">{results.map((r,i)=><article className="card" key={`${r.kind}-${r.chunk?.id||r.khassida.id}-${i}`}><div><span className={`badge ${r.khassida.is_verified?"verified":""}`}>{r.khassida.is_verified?"✓ Contenu vérifié":"Brouillon"}</span>{r.score&&<span className="badge"> pertinence {Math.round(r.score*100)}%</span>}</div><h3>{r.khassida.title}</h3>{r.khassida.arabic_title&&<p className="arabic">{r.khassida.arabic_title}</p>}{r.chunk?<><p className="arabic">{r.chunk.arabic_text}</p><p>{r.chunk.french_translation||r.chunk.transcription}</p><small className="muted">{reference(r.chunk)}</small></>:<p className="muted">{r.khassida.description}</p>}<p>{r.khassida.themes.map(t=><span className="badge" key={t}>{t}</span>)}</p><a className="button secondary" href={`/khassidas/${r.khassida.slug}`}>Voir la fiche</a></article>)}</div>{!loading&&!error&&!results.length&&<div className="panel"><h3>Aucun contenu validé trouvé</h3><p className="muted">Essayez une variante du titre ou un passage plus court.</p></div>}</section>}
function reference(c:Chunk){return [c.chapter_number&&`chapitre ${c.chapter_number}`,c.verse_start&&`vers ${c.verse_start}${c.verse_end?`–${c.verse_end}`:""}`,c.page_number&&`page ${c.page_number}`].filter(Boolean).join(" · ")}
