"use client";
import {FormEvent,useEffect,useState} from "react";
import type {Khassida,Chunk} from "@/types/database";
type Result={kind:"khassida"|"chunk";khassida:Khassida;chunk?:Chunk;score?:number};
export function SearchExperience(){const [q,setQ]=useState("");const [results,setResults]=useState<Result[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 async function search(e?:FormEvent){e?.preventDefault();setLoading(true);setError("");try{const res=await fetch(`/api/search?q=${encodeURIComponent(q)}`);const body=await res.json();if(!res.ok)throw new Error(body.error);setResults(body.results)}catch(err){setError(err instanceof Error?err.message:"Recherche impossible")}finally{setLoading(false)}}
 useEffect(()=>{search()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 return <section id="bibliotheque" className="library-section"><div className="search-wrap container"><form className="searchbar" onSubmit={search}><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher un khassida, un vers, un thème…" aria-label="Rechercher"/><button disabled={loading} aria-label="Lancer la recherche">{loading?"…":"⌕"}</button></form><div className="search-chips"><button onClick={()=>{setQ("arabe");}}>Recherche en arabe</button><span>▧ PDF</span><span>◉ Audio</span><span>✦ Thèmes</span><span>Bibliothèque</span></div></div><div className="container works-block"><div className="section-head"><div><span className="eyebrow">À découvrir</span><h2>Khassaïdes populaires</h2></div><a href="#bibliotheque">Voir tout →</a></div>{error&&<p className="notice">{error}</p>}<div className="works-grid">{results.map((r,i)=><a className="work-card" href={`/khassidas/${r.khassida.slug}`} key={`${r.kind}-${r.chunk?.id||r.khassida.id}-${i}`}><span className={`verify-dot ${r.khassida.is_verified?"on":""}`}>✓</span>{r.khassida.arabic_title&&<p className="arabic">{r.khassida.arabic_title}</p>}<h3>{r.khassida.title}</h3>{r.chunk&&<small>{reference(r.chunk)}</small>}<div>PDF · Audio · Texte</div></a>)}</div>{!loading&&!error&&!results.length&&<div className="empty-library"><div className="empty-icon">خ</div><h3>Le corpus est en préparation</h3><p>Les khassaïdes apparaîtront ici dès leur validation par l’équipe éditoriale.</p><a className="button" href="/admin">Ouvrir l’administration</a></div>}</div></section>}
function reference(c:Chunk){return [c.chapter_number&&`chapitre ${c.chapter_number}`,c.verse_start&&`vers ${c.verse_start}${c.verse_end?`–${c.verse_end}`:""}`,c.page_number&&`page ${c.page_number}`].filter(Boolean).join(" · ")}
